### ISSUE TITLE
404 on OMGYAY image

### ISSUE THREAD

**Issue by ecarlisle** [charmCityJs/charmcityjs.github.io#10]
Homepage GIF is 404.

![image](https://cloud.githubusercontent.com/assets/452134/23081149/842f596c-f521-11e6-8de4-325b5f849dac.png)

GIF was at: http://45.media.tumblr.com/ac243bf640b808c6fbef79df9de364a4/tumblr_ny47gcL05G1uikjs1o1_500.gif

cc: @jasonrhodes , @esauter5

**Comment by skratchdot** [comment]
https://web.archive.org/web/20160918202159im_/http://45.media.tumblr.com/ac243bf640b808c6fbef79df9de364a4/tumblr_ny47gcL05G1uikjs1o1_500.gif

**Comment by skratchdot** [comment]
From: https://web.archive.org/web/20160918202159im_/http://45.media.tumblr.com/ac243bf640b808c6fbef79df9de364a4/tumblr_ny47gcL05G1uikjs1o1_500.gif

![oh-yeah](https://cloud.githubusercontent.com/assets/434470/23089453/f789061c-f556-11e6-8512-e157467d2047.gif)

**Comment by clickclickonsal** [comment]
Fixed in pull request #12
