### ISSUE TITLE
slack widgit silently fails

### ISSUE THREAD

**Issue by latazzajones** [charmCityJs/charmcityjs.github.io#4]
If a user was previously invited via the widget or another person .. another invitation cannot be sent and the widget silently fails instead of re-sending the original invitation. :sadface:

**Comment by ecarlisle** [comment]
It looks like the widget in place is a [Slackin](http://rauchg.com/slackin/) server deployed to Heroku, though I can't tell what version.  After looking at similar projects, Slackin looks to have the most activity / forks / stars.  [This issue](https://github.com/rauchg/slackin/issues/44) might be related, but it's a year old and is still open.  There's a chance that if we update to the latest stable version we might have different results, but that's just speculative.
